name: Deploy to GH pages
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: 'package-lock.json'
      - name: Install all dependencies
        run: npm install
      - name: Remove .gitignore file
        run: rm .gitignore
      - name: Deploy to gh-pages
        run: |
          git config --global user.email "sergio.illarionov@gmail.com"
          git config --global user.name "Serhii Illarionov"
          npm run deploy
