name: Deploy to GH pages
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node 16
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
          cache-dependency-path: 'package-lock.json'
      - name: Install dependencies
      - run: npm install
      - name: Create production build
      - run: npm run build
      - name: Deploying the static website to gh-pages
      - run: npm run deploy
